{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "source": [
    "import sys\n",
    "sys.path.append('../')\n",
    "from data.datasets import PureCompounds\n",
    "from data.data_functions import DataLoader, DerivTransform, NormalizeTransform\n",
    "from data.experiment_parameters import ExperimentFilter, Chamber, Sensor, InjectionTime, InjectionRate, InjectionVolume, DataFilter"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "source": [
    "chem_list = ['Pentane', 'Hexane','Heptane','Octane','Nonane','Decane','Toluene']\n",
    "filters = ExperimentFilter(Chamber('tall'), Sensor('SM30_Sensor'), InjectionTime(15.0), InjectionRate(6.0), InjectionVolume(1.3))\n",
    "exp_derivs, labels = DataLoader(PureCompounds(chem_list, filters=filters), transforms=[DerivTransform, NormalizeTransform]).load()"
   ],
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Loading experimental data\n",
      "Pentane (1/7): [===================0] 100% complete\n",
      "Hexane (2/7): [===================0] 100% complete\n",
      "Heptane (3/7): [===================0] 100% complete\n",
      "Octane (4/7): [===================0] 100% complete\n",
      "Nonane (5/7): [===================0] 100% complete\n",
      "Decane (6/7): [===================0] 100% complete\n",
      "Toluene (7/7): [===================0] 100% complete\n",
      "Length of experimental set loaded: 45\n"
     ]
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "source": [
    "from data.experiment_parameters import _create_experiment_label_df, create_physical_property_label, create_concentration_label\n",
    "\n",
    "physical_properties = create_physical_property_label(labels.keys(), 'Vapor Pressure', 'Boiling Point', 'Flash Point', 'Viscosity')\n",
    "#create_concentration_label(labels.keys())"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "markdown",
   "source": [
    "# Alkanes only"
   ],
   "metadata": {}
  },
  {
   "cell_type": "markdown",
   "source": [
    "## Dataset split (train-test)\n",
    "\n",
    "Perform a stratified train-test split based on the class labels"
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "alkane_labels = {k:v for k,v in labels.items() if v.lower()!='toluene'}\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(list(alkane_labels.keys()), list(alkane_labels.values()), test_size=0.2, shuffle=True, stratify=list(alkane_labels.values()))"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "markdown",
   "source": [
    "## Model training"
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.svm import SVR\n",
    "from sklearn.model_selection import cross_validate, GridSearchCV"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "markdown",
   "source": [
    "### Gridsearch\n",
    "\n",
    "Do on one property only"
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "source": [
    "svm = SVR()"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Coarse grid search"
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "source": [
    "clf = svm.fit(X,y)\n",
    "clf.score(X,y)"
   ],
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "-0.2500773123814348"
      ]
     },
     "metadata": {},
     "execution_count": 35
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "source": [
    "print(clf.predict(X[:2]), y[:2])"
   ],
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "[6.19089581 5.22695024] [18.477418996839496, 0.4082808106380722]\n"
     ]
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "source": [
    "param_grid = {'C': [pow(10,n) for n in range(-8, 9, 2)], 'kernel': ['linear']}\n",
    "\n",
    "X = [exp_derivs[exp] for exp in X_train]\n",
    "y = [physical_properties[exp].Vapor_Pressure for exp in X_train]\n",
    "\n",
    "grid_search = GridSearchCV(svm, param_grid, scoring='accuracy', cv=5, return_train_score=True)\n",
    "hpo_coarse_results = grid_search.fit(X, y)"
   ],
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 199, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 242, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred,\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 202, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py\", line 100, in _check_targets\n",
      "    raise ValueError(\"{0} is not supported\".format(y_type))\n",
      "ValueError: continuous is not supported\n",
      "\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan]\n",
      "  warnings.warn(\n",
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the train scores are non-finite: [nan nan nan nan nan nan nan nan nan]\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [
    "pd.DataFrame(hpo_coarse_results.cv_results_)[['param_C', 'mean_train_score', 'mean_test_score']].pivot_table(columns=['param_C'])"
   ],
   "outputs": [
    {
     "output_type": "display_data",
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th>param_C</th>\n",
       "      <th>1.000000e-08</th>\n",
       "      <th>1.000000e-06</th>\n",
       "      <th>1.000000e-04</th>\n",
       "      <th>1.000000e-02</th>\n",
       "      <th>1.000000e+00</th>\n",
       "      <th>1.000000e+02</th>\n",
       "      <th>1.000000e+04</th>\n",
       "      <th>1.000000e+06</th>\n",
       "      <th>1.000000e+08</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>mean_test_score</th>\n",
       "      <td>0.166667</td>\n",
       "      <td>0.166667</td>\n",
       "      <td>0.166667</td>\n",
       "      <td>0.166667</td>\n",
       "      <td>0.366667</td>\n",
       "      <td>0.816667</td>\n",
       "      <td>0.85</td>\n",
       "      <td>0.85</td>\n",
       "      <td>0.85</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean_train_score</th>\n",
       "      <td>0.183333</td>\n",
       "      <td>0.183333</td>\n",
       "      <td>0.183333</td>\n",
       "      <td>0.183333</td>\n",
       "      <td>0.408333</td>\n",
       "      <td>0.970833</td>\n",
       "      <td>1.00</td>\n",
       "      <td>1.00</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "param_C           1.000000e-08  1.000000e-06  1.000000e-04  1.000000e-02  \\\n",
       "mean_test_score       0.166667      0.166667      0.166667      0.166667   \n",
       "mean_train_score      0.183333      0.183333      0.183333      0.183333   \n",
       "\n",
       "param_C           1.000000e+00  1.000000e+02  1.000000e+04  1.000000e+06  \\\n",
       "mean_test_score       0.366667      0.816667          0.85          0.85   \n",
       "mean_train_score      0.408333      0.970833          1.00          1.00   \n",
       "\n",
       "param_C           1.000000e+08  \n",
       "mean_test_score           0.85  \n",
       "mean_train_score          1.00  "
      ]
     },
     "metadata": {}
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Fine grid search"
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [
    "param_grid = {'C': [pow(10,n) for n in np.linspace(1,4,11)], 'kernel': ['linear']}\n",
    "\n",
    "grid_search = GridSearchCV(svm, param_grid, scoring='accuracy', cv=5, return_train_score=True)\n",
    "hpo_coarse_results = grid_search.fit([exp_derivs[exp] for exp in X_train], y_train)"
   ],
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_split.py:666: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.\n",
      "  warnings.warn((\"The least populated class in y has only %d\"\n"
     ]
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [
    "pd.DataFrame(hpo_coarse_results.cv_results_)[['param_C', 'mean_train_score', 'mean_test_score']].pivot_table(columns=['param_C'])"
   ],
   "outputs": [
    {
     "output_type": "display_data",
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th>param_C</th>\n",
       "      <th>10.000000</th>\n",
       "      <th>19.952623</th>\n",
       "      <th>39.810717</th>\n",
       "      <th>79.432823</th>\n",
       "      <th>158.489319</th>\n",
       "      <th>316.227766</th>\n",
       "      <th>630.957344</th>\n",
       "      <th>1258.925412</th>\n",
       "      <th>2511.886432</th>\n",
       "      <th>5011.872336</th>\n",
       "      <th>10000.000000</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>mean_test_score</th>\n",
       "      <td>0.733333</td>\n",
       "      <td>0.766667</td>\n",
       "      <td>0.750000</td>\n",
       "      <td>0.850000</td>\n",
       "      <td>0.816667</td>\n",
       "      <td>0.85</td>\n",
       "      <td>0.85</td>\n",
       "      <td>0.85</td>\n",
       "      <td>0.85</td>\n",
       "      <td>0.85</td>\n",
       "      <td>0.85</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean_train_score</th>\n",
       "      <td>0.808333</td>\n",
       "      <td>0.900000</td>\n",
       "      <td>0.954167</td>\n",
       "      <td>0.966667</td>\n",
       "      <td>0.987500</td>\n",
       "      <td>1.00</td>\n",
       "      <td>1.00</td>\n",
       "      <td>1.00</td>\n",
       "      <td>1.00</td>\n",
       "      <td>1.00</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "param_C           10.000000     19.952623     39.810717     79.432823     \\\n",
       "mean_test_score       0.733333      0.766667      0.750000      0.850000   \n",
       "mean_train_score      0.808333      0.900000      0.954167      0.966667   \n",
       "\n",
       "param_C           158.489319    316.227766    630.957344    1258.925412   \\\n",
       "mean_test_score       0.816667          0.85          0.85          0.85   \n",
       "mean_train_score      0.987500          1.00          1.00          1.00   \n",
       "\n",
       "param_C           2511.886432   5011.872336   10000.000000  \n",
       "mean_test_score           0.85          0.85          0.85  \n",
       "mean_train_score          1.00          1.00          1.00  "
      ]
     },
     "metadata": {}
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "markdown",
   "source": [
    "### Cross-validation/dev"
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [
    "svm = SVR(C=300, kernel='linear')"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [
    "cv_results = cross_validate(svm, [exp_derivs[exp] for exp in X_train], y_train, scoring='accuracy', cv=5, return_train_score=True, return_estimator=True)\n",
    "{key:cv_results[key] for key in cv_results if key != 'estimator'}"
   ],
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "/Applications/anaconda3/envs/torch/lib/python3.8/site-packages/sklearn/model_selection/_split.py:666: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.\n",
      "  warnings.warn((\"The least populated class in y has only %d\"\n"
     ]
    },
    {
     "output_type": "display_data",
     "data": {
      "text/plain": [
       "{'fit_time': array([0.0034771 , 0.0014441 , 0.00178099, 0.00141501, 0.00142407]),\n",
       " 'score_time': array([0.00067592, 0.00046587, 0.00067115, 0.00048494, 0.00045013]),\n",
       " 'test_score': array([0.91666667, 0.91666667, 0.83333333, 0.75      , 0.83333333]),\n",
       " 'train_score': array([1., 1., 1., 1., 1.])}"
      ]
     },
     "metadata": {}
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [
    "class Ens:\n",
    "    def __init__(self, estimators):\n",
    "        self.estimators = estimators\n",
    "        self._estimator_type = 'classifier'\n",
    "        \n",
    "    def predict(self, X):\n",
    "        final = []\n",
    "        for x in X:\n",
    "            predictions = []\n",
    "            for est in self.estimators:\n",
    "                predictions.append(est.predict([x])[0])\n",
    "            final.append(max(set(predictions), key=predictions.count))\n",
    "        return np.array(final)"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [
    "single = svm.fit([exp_derivs[exp] for exp in X_train], y_train)\n",
    "ensemble = Ens(cv_results['estimator'])"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "markdown",
   "source": [
    "### Metrics"
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [
    "from matplotlib import pyplot as plt\n",
    "from sklearn.metrics import plot_confusion_matrix"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [
    "_, ax = plt.subplots(1,2, figsize=(10,4))\n",
    "\n",
    "print(single.score([exp_derivs[exp] for exp in X_test], y_test))\n",
    "\n",
    "plt.plot(y_test, single.predict(X_test))\n",
    "plt.plot(y_test, ensemble.predict(X_test))"
   ],
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "0.6875\n"
     ]
    },
    {
     "output_type": "display_data",
     "data": {
      "text/plain": [
       "<sklearn.metrics._plot.confusion_matrix.ConfusionMatrixDisplay at 0x7ff8579f0460>"
      ]
     },
     "metadata": {}
    },
    {
     "output_type": "display_data",
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAowAAAEDCAYAAAC/PVVGAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8rg+JYAAAACXBIWXMAAAsTAAALEwEAmpwYAABX0klEQVR4nO29e5xXVb3//3zNMNwFQ5AAIUgJNTVUwuu3MEvt/DqHSr5ejueUlaIdL2lZx45WZEdPlqWVliEp2Te1wkozT5AmahoqKKioKOIV8AKIyH2Yef/+WOsD23E+n9kz7PnM3h/ez8djP2bvtdd67/dan71fs257bZkZjuM4juM4jlOOuq52wHEcx3Ecx8k3XmF0HMdxHMdxKuIVRsdxHMdxHKciXmF0HMdxHMdxKuIVRsdxHMdxHKciXmF0HMdxHMdxKuIVRsdxdlgkDZd0l6QnJC2U9KVW4kjSjyUtlvSopAMS5z4r6Zm4fba63juOsyNTbf2Sr8PoOM6OiqQhwBAze1jSTsA84JNm9kQizj8BZwH/BBwE/MjMDpI0AJgLjAMspj3QzN6odj4cx9nxqLZ+eQ+j4zg7LGa23MwejvtvAU8Cw1pEmwhcb4E5wM5RqI8G/mpmq6LI/hU4poruO46zA1Nt/fIKo+M4DiBpJLA/8ECLU8OAlxLHL8ewcuGO4zhVpRr61W27vXQcx6kiRx/R21asak4V9+FHNy0ENiaCpprZ1JbxJPUFbgbOMbM1mTjqOI7TCmk1LG/65RVGx3EKxYpVTdz/l3QdeT2HPrfRzMZViiOpgSC2vzaz37cSZSkwPHG8WwxbCkxoET47lWOO4+ywpNWwvOmXD0k7jlMoDGjGUm1tIUnAL4AnzeyHZaLdCnwmvm14MPCmmS0HZgJHSXqXpHcBR8Uwx3GcsqTVsLaotn55D6PjOIWjmXRD0ik4DPh34DFJ82PYfwEjAMzsauB2whuGi4H1wOfiuVWSvgM8FNNdZGarsnLMcZzaJSMNq6p+eYXRcZxCYRhNGS0HZmZ/B9RGHAPOKHPuWuDaTJxxHGeHICsNq7Z+eYXRcZzCkWa4xnEcJ68UUcO8wug4TqEwoDG7IWnHcZyqUlQN8wpjJzFwQL2NHN6w3XaefrR3Bt44Tj7ZyDo226aKQyotMchsSNppHdcvx0nHW7yxwswGtSdNUTXMK4ydxMjhDTw4c3jbEdvg6KFjt98Zx8kpD9idHUpXvLZ5sXD9cpx03GEzXuhIuiJqmFcYHccpFIbRVMD5P47jOFBcDfMKo+M4xcKgqXha6ziOEyiohnmF0XGcQhEWvXUcxykmRdUw/9JLlXltaQNfnbQ7p354T06dMIY/TBu4XfbGTVjDtHuf4rr7nuS4M1/tcjvuU3Xt1LpPrWGIRku3OdmTpYbl8Z7Lmx33qdg+tUZaDcsbua8wSvqkJJO0ZwfTnyxpaNZ+dZT6bsbkby7jmruf4ke3PcOfpg/khad7dMhWXZ1xxiVLufCkUZw6YQxHTFzNiNEb207YSXbcp+raqXWfKtGEUm1dTa3pF2SnYXm85/Jmx30qtk+VKIJ+tST3FUbgRODv8W9HOBnIjeDuMngLo/fbAEDvvs0M32MTK5Z3bPmKMfuvZ9nz3XnlxR5saaxj9i07c8jRb3aZHfepunZq3adyGMWpMFJj+gXZaVge77m82XGfiu1TOdJqWN7IdYVRUl/gcOALwAkxrF7SZZIel/SopLNi+IGS7pY0T9JMSUMkTQLGAb+WNF9SL0lHSnpE0mOSrpXUI6Z/XtK3JT0cz+0Zw/vEeA/GdBOzyt8rL3Xn2cd7secB6zuUfpd3N/L6su5bj1csb2DgkMYus+M+VddOrftUiWZTqq0rqXX9gu3TsDzec3mz4z4V26dK5F2/WiPXFUZgIvAXM3saWCnpQGAyMBIYa2b7EcS0AfgJMMnMDiR8G/FiM5sBzAVOMrOxhIr9dOB4M9uX8NLPFxPXW2FmBwA/A86LYRcAfzOz8cARwPcl9WnNWUmTJc2VNPf1lU0VM7ZhXR3fOWUkp1+0lD47FXH6q+N0DQXqYaxZ/QLXMMfpKN7D2DmcCNwU92+Kxx8Ffm5mWwDMbBUwBtgH+Kuk+cCFwG6t2BsDPBcFHOCXwIcS538f/84jiDrAUcD50e5soCcwojVnzWyqmY0zs3GDdqkvm6ktjfCdU0bykU+/weH/1PGu7pWvNDBo6OatxwOHNHZoaCgrO+5Tde3Uuk/lCBPG61NtXUxN6hdko2F5vOfyZsd9KrZP5UirYXkjtxVGSQOAjwDTJD0PfBU4rlx0YKGZjY3bvmZ2VAcuuyn+bWLbkkMCjk3YHmFmT3bANgBm8MOvjGD46E0ce9rrHTUDwKL5vRk2ajODh2+iW0MzEyauZs6s/l1mx32qrp1a96kcRehhrFX9guw0LI/3XN7suE/F9qkcRe1hzPM6jJOAX5nZaaUASXcDC4DTJN1lZluiMC8CBkk6xMz+EYd43mdmC4G3gJ2iiUXASEl7mNli4N+Bu9vwYyZwlqSzzMwk7W9mj3Q0Uwsf7MOdMwYwaq8NfPGjYwD43NeXMf7It9ptq7lJXHXBMC65YQl19TDrpgG88HTPLrPjPlXXTq37VB7RZLlt65aoSf2C7DQsj/dc3uy4T8X2qTyF0LB3IMvpB7Al3QVcamZ/SYSdDewFbACOARqBa8zsSkljgR8D/QkV4SvM7BpJxwKXxDSHAIcCl8U4DwFfNLNNsRdgnJmtkDQOuMzMJkjqBVwR09URhoQ+0Zb/4z7Q0/xbrI5TmQfsTtbYqnY1pcfs19Om3trqqOo7mDDqmXlmNq5Dzm0Hrl8B1y+n1rnDZrRbY9JqWFfpVzly28NoZke0EvbjxOGXW5ybz9vn85TCbwZuTgTdCezfSryRif25wIS4vwE4rWV8x3G6jjwO1yRx/XIcpxJ517DWyG2F0XEcpzXMijmc4ziOA8XVMK8wOo5TKAxoJJs3CCVdC3wCeM3M9mnl/FeBk+JhN8KQ8iAzWxWHgd8ivGSyJU9DR47j5JeialjxqriO4+zghNZ5mi0F0wnzCVvFzL5fesMY+Dpwd1wKp8QR8bxXFh3HSUk6DUvJdKqkYd7D2Ek89sYgdv/N6dttZw/mZOCN49QOBjRn1NY1s3skjUwZ/UTgxkwunHNcvxyn8yiqhnkPo+M4haPJlGrLCkm9Ca345AsoBsyKn/ObnNnFHMepeaqpX5CNhnkPo+M4hcIQTenbugMlzU0cTzWzqR247D8D97UYyjnczJZK2pXwlZanzOyeDth2HGcHoh0alpV+QQYa5hVGx3EKR3P6+T0rMppfeAIthnLMbGn8+5qkPwDjAa8wOo7TJik1LCv9ggw0zIekHccpFM2IzVafassCSf2BDwO3JML6SNqptE/4ZvPjmVzQcZyaJq2GZUVWGuYVxi5g1xufZeQ35jL80gXbbWvchDVMu/cprrvvSY4789Uut+M+VddOrftUjmbqUm1tIelG4B/AGEkvS/qCpNMlJd/4+BQwy8zWJcIGA3+XtAB4EPhz8qsutUwe9StLW3mz4z4V26dyZKFfUF0N69QKo6RPSjJJe3Yw/cmShm7H9f9F0vkJX/auEPd0SZ+J+9MlTeroddtizfhBLJ+813bbqaszzrhkKReeNIpTJ4zhiImrGTF6Y5fZcZ+qa6fWfSqHGZktq2NmJ5rZEDNrMLPdzOwXZna1mV0NQTeA64ApLdItMbMPxO39ZnZxa/ZrUcPypl9Z2sqbHfep2D6VI62GpbNVWcNinOlmdkKLdKk0LEln9zCeCPw9/u0IJwMdFlszu9XMvhsPPwm0KraSusUCvr6j12oPG3fvR1Of7e9uHrP/epY9351XXuzBlsY6Zt+yM4cc/WaX2XGfqmun1n0qj2hOuWWAa1gL8qZfWdrKmx33qdg+ladq+pUpnVZhlNQXOBz4AmGyJZLqJV0m6XFJj0o6K4YfKOnu+Gr3TElDYut4HPBrSfMl9ZJ0pKRHJD0m6VpJPWL65yV9W9LD8dyeMfxkSVdKOhT4F+D70dbukmZLuiK+gfQlSVMknddKPt7hW2eVWXvZ5d2NvL6s+9bjFcsbGDikscvsuE/VtVPrPpXDyK6HsRKuYZ1LHu+5vNlxn4rtUznSalje6EyPJgJ/MbOngZWSDgQmAyOBsWa2H0FIG4CfAJPM7EDgWuBiM5sBzAVOiiuUG2FF8+PNbF/CG95fTFxvhZkdAPwMeJtomtn9wK3AV+OK5s/GU93NbJyZ/aC1DJTzbXsKxXGc7cMQjVafattOXMMcx8mctBqWNzpzWZ0TgR/F/Zvi8SjgajPbAhC/ZbgPsA9hDSCAemB5K/bGAM9F8Qb4JXAGcEU8/n38Ow/4dEoff9PG+TEpfQNAYeHLyQD173pXShc6zspXGhg0dPPW44FDGlmxvKHL7LhP1bVT6z5Voh3rMG4PO5SGFVW/srSVNzvuU7F9qkSVNCxTOsVjSQOAjwDTFD5u/VXguHLRgYWlbx2a2b5mdlQHLrsp/m0ifUV4XRvn2+WbmU2Nrf1x9X37pHSh4yya35thozYzePgmujU0M2HiaubM6t9ldtyn6tqpdZ/KYYQ1zNJsHWVH1LCi6leWtvJmx30qtk/lSKtheaOzehgnAb8ys9NKAZLuBhYAp0m6y8y2RFFeBAySdIiZ/SMOobzPzBYCbwE7RROLgJGS9jCzxcC/A3e3w6ekrbRU8q3DDL7+GXotXkP9ui2MnPIwK4/ZjbcO3rXddpqbxFUXDOOSG5ZQVw+zbhrAC0/37DI77lN17dS6T+URTZ0/Idw1rAx5068sbeXNjvtUbJ/KUxUNyxyZWfZGpbuAS5Nr+kg6G9gL2ED4nmEjcI2ZXSlpLPBjoD+hEnuFmV0j6VjgkpjmEOBQ4LIY5yHgi2a2KfYAjDOzFZLGAZeZ2QRJJ8fwMyUdBlxDaMVPAn4BnGdmc6N/U4C1ZnaZpOnAbWY2o5xvbZVBjxHDbehXzulQ+SXZ49w5223DcfLKA3Yna2xVu5Rzt33629m/PTRV3P98/1/mWQe+lLCja5jrl+Ok4w6b0W6NSathHdWvzqJTKoyOC67jpKGjFcYzfntYqrj/9f7/zZXgFgXXL8dJR0crjGk0LG/65d+SdhynUJiJxmaXLsdxiklRNax4HjuOs0NjkMtFbR3HcdJQVA3zCqPjOAVDuVzU1nEcJx3F1DCvMDqOUyjCkhTFa507juNAcTXMK4ydRI+X1uVuwvfiyw/OxE7e8uXseBRx0dsi4frlOJ1LETXMK4yO4xQKQ2zJ4WezHMdx0lBUDfMKo+M4hcIMmgo4nOM4jgPF1TCvMDqOUziKOP/HcRynRBE1zCuMjuMUCkO5/M6q4zhOGoqqYcXzuAYYN2EN0+59iuvue5Ljznw1F7Z2vfFZRn5jLsMvXbBd/mTpUx7LKW92at2ncjTFb7G2tTmdQ97uOdcv9ymvPpWjiPpVmAqjpCZJ8yUtlLRA0lckFcb/EnV1xhmXLOXCk0Zx6oQxHDFxNSNGb+xyW2vGD2L55L06lLYzfMpjOeXNTq37VI7SkhRptrxQK/oF+bznXL/cpzz6VI60GpY3iiRYG8xsrJm9H/gY8HHgW13sU7sZs/96lj3fnVde7MGWxjpm37Izhxz9Zpfb2rh7P5r6bP9bW1n5lMdyypudWvepPOENwzRbm5akayW9JunxMucnSHozVvbmS/pm4twxkhZJWizp/DYuVRP6Bfm851y/3Kc8+lSedBqWylL1NKxQFcatmNlrwGTgTAXqJX1f0kOSHpV0WimupP+U9Fhs1X83hp0a4y6QdLOk3jF8uqQfS7pf0hJJkxJ2vpqw/+2O+r7Luxt5fVn3rccrljcwcEhjl9vKiqx8ymM55c1OrftUjtIbhmm2FEwHjmkjzr2xsjfWzC4CkFQPXEWo+O0NnChp73T+F1e/IJ/3XFbkMW/uU3F9KkdaDUvJdKqkYYWsMAKY2RKgHtgV+ALwppl9EPggcKqkUZI+DkwEDjKzDwDfi8l/b2YfjGFPxvQlhgCHA58ASgJ9FDAaGA+MBQ6U9KGWPkmaLGmupLmNbMo8z47jBJqtLtXWFmZ2D7CqAy6MBxab2RIz2wzcRNCaVLh+Oc6OTRb6BdXVsFp5S/ooYL9Ei7o/QSA/ClxnZusBzKxUqPtI+m9gZ6AvMDNh649m1gw8IWlwwv5RwCPxuG+0f0/SCTObCkwF6KcB1pqjK19pYNDQzVuPBw5pZMXyhvbmN3NbWZGVT3ksp7zZqXWfyhHeMEzd+h4oaW7ieGp8TtvDIZIWAMuA88xsITAMeCkR52XgoHbaLVEY/YJ83nNZkce8uU/F9akc7dCwLPQLMtKwwvYwSnov0AS8Bgg4K9HlOsrMZlVIPh0408z2Bb4N9EycSzatlfj7Pwn7e5jZLzri96L5vRk2ajODh2+iW0MzEyauZs6s/h0xlamtrMjKpzyWU97s1LpPlWhGqTZghZmNS2ztFduHgffE3ryfAH/Mwv+i6hfk857LijzmzX0qrk+VqJJ+QYYaVsgeRkmDgKuBK83MJM0Evijpb2bWKOl9wFLgr8A3Jf3azNZLGhBb6TsByyU1ACfFuJWYCXwn2lkraRjQGOcitYvmJnHVBcO45IYl1NXDrJsG8MLTPdtO2Mm2Bl//DL0Wr6F+3RZGTnmYlcfsxlsH79plPuWxnPJmp9Z9KkfpDcNqYGZrEvu3S/qppIEEzRieiLobbesIUGz9gnzec65f7lMefSpHUTVMZmVHHnKFpCbgMaAB2AL8CvihmTUrLE/x38A/E1rTrwOfNLM345s/nwE2A7eb2X9J+iLwtRjvAWAnMztZ0nTgNjObEa+51sz6xv0vAadEd9YC/2Zmz5bzt58G2EE6MttC2E4WX35wJnb2OHdOJnYc5wG7kzW2ql3KOWDPXe3Ia49NFXfGYVfPM7NxleJIGkl47vdp5dy7gVdjxW48MAN4D2H+4dPAkQSRfQj41zjU09o1XL+2E9cvJ4/cYTPa1JiWpNWwNPoF1dEwKFAPo1n5d8zjnJ3/ilvLc98lTv5OhP0M+FkrcU9ucdw3sf8j4Eft9dtxnGwxKA3XbDeSbgQmEOYKvUxY6qYBwMyuBiYRev+2ABuAEyy0srdIOpPQe1cPXFtJaF2/HMcpUUQNgwJVGB3HcUpkNZxjZie2cf5K4Moy524Hbs/EEcdxdiiKqGFeYXQcp1BUc/6P4zhO1hRVw7zC6DhO4Sii2DqO45QoooZ5hXEHIqvJ3llNPgefgO60H0NsSbmorVM7uH45tUJRNcwrjI7jFAsrZuvccRwHKKyGeYXRcZxCUdT5P47jOFBcDfMKo+M4haOIYus4jlOiiBrmFUbHcQpFO78l7TiOkyuKqmHFm3VZA4ybsIZp9z7Fdfc9yXFnvpoLW1nZ2fXGZxn5jbkMv3RBh21k7VOWtvJmp9Z9KoeZUm1O51Cr95zrl/uUtU/lKKJ+FabCKKlJ0vzEdn4MP0dS70S8tVXwpcPXqKszzrhkKReeNIpTJ4zhiImrGTF6Y5faytKnNeMHsXzyXh1K21k+5a2cajlvWdtqDTPYYnWptrxQK/oFtX3PuX65T52tX5Bew/JG/jwqzwYzG5vYSp/LOgfoXSFdrhiz/3qWPd+dV17swZbGOmbfsjOHHP1ml9rK0qeNu/ejqU/Zr6B1iU95K6dazlvWtspRwB7GmtAvqO17zvXLfaqGfoH3MFYdSWcDQ4G7JN2VCL9Y0gJJcyQNjmH/LOkBSY9IuiMRPkXStZJmS1oSbZbsfFnS43E7Jwufd3l3I68v6771eMXyBgYOaexSW1n6lBW1XE61nLesbbVOmP+TZsszRdQv2FHvua7zp5bLu9Z9Kk8x9atIFcZeLYZ0jjezHwPLgCPM7IgYrw8wx8w+ANwDnBrD/w4cbGb7AzcBX0vY3hM4GhgPfEtSg6QDgc8BBwEHA6dK2r+Sg5ImS5oraW4jm7LJteM476CAPYyuX47jbKVg+gUU6y3pDWY2NkW8zcBtcX8e8LG4vxvwG0lDgO7Ac4k0fzazTcAmSa8Bg4HDgT+Y2ToASb8H/g/wSLkLm9lUYCpAPw2w1uKsfKWBQUM3bz0eOKSRFcsbUmSr82xl6VNW1HI51XLesrbVGgVdw6wm9At2zHuuK/2p5fKudZ/KUVANK1QPY1oazawkdk1sqxT/BLjSzPYFTgN6JtIkm9PJNJmzaH5vho3azODhm+jW0MyEiauZM6t/l9rK0qesqOVyquW8ZW2rVSxMGk+zFZBc6xfsoPdcF/pTy+Vd6z6VpaD6VaQexnK8BewErGgjXn9gadz/bAq79wLTJX0XEPAp4N876mSJ5iZx1QXDuOSGJdTVw6ybBvDC0z3bTtiJtrL0afD1z9Br8Rrq121h5JSHWXnMbrx18K5d6lPeyqmW85a1rdYwoCmHbxB2kELpF9T2Pef65T51tn5BcTVMlsdqbCtIagIeSwT9xczOl3QWcCawzMyOkLTWzPrGNJOAT5jZyZImApcDbwB/Az5oZhMkTQHWmtllMc3jMc3zkr4MfD5eb5qZXRHjbL1GOfppgB2kIzPKfb5YfPnBmdna49w5mdlyiscDdidrbFW7xmZ6jx5q77viC6niLvjEf88zs3Edci5DXL/yg+uXkyV32Ix2a0xaDcuLfpUoTA+jmbW61oGZ/YQwXFM67pvYnwHMiPu3ALe0kn5Ki+N9Evs/BH7YSpqKYus4TudSkHbuVly/HMdJUjQNgwJVGB3HcUrk8Q1Cx3GctBRRw4o3iO44zg5NmBCezbI6cQ3D1+JQbmvnT5L0qKTHJN0v6QOJc8/H8PmS5maYRcdxapi0GpaGamqY9zA6jlM4mpoza51PB64Eri9z/jngw2b2hqSPE5adOShx/ggza+uFFcdxnLdRRA3zCqPjOIUjq+EcM7tH0sgK5+9PHM4hrIfoOI6zXRRRw7zC6LSbPL4Z6G8+7jgY7foKwsAWQy1T4wLVHeELwP++zRWYJcmAn2+HXaeK5PH5dv3asWiHhmWpX7CdGuYVRsdxCkc7XjBckcWyFJKOIIjt4Yngw81sqaRdgb9KesrM7tneazmOU/uk1LBM9Auy0TB/6cVxnGKR4UsvaZC0HzANmGhmK7e6YbY0/n0N+APhW86O4ziVyfCllzRkpWFeYXQcp3hYym07kTQC+D3w72b2dCK8j6SdSvvAUUCrbyk6juO8gyroF2SrYV5h7ALGTVjDtHuf4rr7nuS4M1/Nha1a9mnXG59l5DfmMvzSBR22kbVPtVzeWdtqjeZmpdraQtKNwD+AMZJelvQFSadLOj1G+SawC/DTFktPDAb+LmkB8CDwZzP7S+YZzSm1fM/lzU4e9StLW7XuUzmy0C+oroaVncMo6SdUqOOa2dmpctMBWn66StLJwDgzO7MDtkYCh5rZDdl52HHq6owzLlnK1094LyuWN/CT259hzsz+vPhM+79VmZWtWvdpzfhBvHn4u9n1hsXtTtsZPtV6eWdpqzWMdr1hOFzSj99hI+qXmZ1Y8VpmpwCntBK+BPjAO1MEXMOqZyePPtWyfmVpq9Z9Kkc7NayyrU7SsNao1MM4F5hXYSsKI4F/7WonSozZfz3Lnu/OKy/2YEtjHbNv2ZlDjn6zS23Vuk8bd+9HU59Wv8zWJT7VenlnaatVDDCl22A9xdYvqFENy+M9lzc7kD/9ytJWrftUlrQaljPKVhjN7JfJDfhdi+MuQdIgSTdLeihuh8XwKZJ+Jekfkp6RdGpM8l3g/8Su2HMljZR0r6SH43ZoTD9B0mxJMyQ9JenXkhTPHSjpbknzJM2UNKSj/u/y7kZeX9Z96/GK5Q0MHNLYpbZq3aesyGPeatmnSoQvJbS9ASvzpF/gGpa1nTz6VMv6laWtWvepEin1K1e0uayOpEOAXwB9gRHxszKnmdl/dKJfvSTNTxwPAG6N+z8CLjezv8fJnDOBveK5/YCDgT7AI5L+DJwPnGdmn4j56Q18zMw2ShoN3AiUXlvfH3g/sAy4DzhM0gPATwhvF70u6XjgYuDznZBvx3HSkF5M+0h6gurqF7iGOY5TiRxWCNsizTqMVwBHE8XOzBZI+lBnOgVsMLOxpYPS/J94+FFg79hwBugnqTRX6BYz2wBskHQX4RXx1S1sNwBXShoLNAHvS5x70MxejtecTxgKWg3sQ1ijCKAeWN6a05ImA5MBetK71YytfKWBQUM3bz0eOKSRFcsbWo3bFlnZqnWfsiKPeatln8rTriUnhhMqY9XULyighqXRL6jtey5vdrKklss7rz6VJ9tlc6pFqrekzeylFkFNneBLWuqAg81sbNyGmdnaeK5lnb21Ovy5wKuEyZ7jgO6Jc5sS+02ECrWAhYnr7WtmR7XmmJlNNbNxZjaugR6tOr9ofm+GjdrM4OGb6NbQzISJq5kzq39bee5UW7XuU1bkMW+17FNZDKxZqTbInX5BTjUsjX5Bbd9zebOTJbVc3nn1qSwpNSxvpOlhfCnOkTFJDcCXgCc7162KzALOAr4PIGmsmc2P5yZK+h/CcM4EwlDOEGCnRPr+wMtm1izps4TWdiUWAYMkHWJm/4hl8D4zW9gR55ubxFUXDOOSG5ZQVw+zbhrAC0937O2rrGzVuk+Dr3+GXovXUL9uCyOnPMzKY3bjrYN37TKfar28s7RVlvTDOZtzpl/gGpapnTz6VMv6laWtWvepIgUckpa1MbNS0kDCnJuPElrGM4EvJVcLz9ypCktSRH+uIgwzdQPuMbPTJU0B3guMBgYC3zOza6I4ziSsQzQduA24mfBz/QU4w8z6SprA2+cJXQnMNbPpcejnxwSh7gZcYWbXVMpDPw2wg3RkBqXhpMG/xVpMHrA7WWOr2tWU7jFqNxvy7bNSxX3hs+cvABZSRf2C4muY61d1cf0qLnfYjHnt/XxfWg174bPnt9t2Z9JmD6OZrQBOqoIvyWv2bXE8nSCUJX+OL5P0UTP7TIu0jcBHWsTbL7H/nzHebGB2It2Zif35QDXmPTmOk4b0rfMtZlZV/QLXMMdx2qCAPYxtzmGU9F5Jf5L0uqTXJN0i6b3VcM5xHKdV0n8asLvrl+M4uaNKnwbMkjRzGG8gDJ98Kh6fQFjG4aDOcqojmNmUrvbBcZwqECeMp+S9hLmCudYvcA1znB2G9mlYbkjzlnRvM/uVmW2J2/8DOmEGqOM4TkrS9zDWuX45jpM7aqmHUdKAuPu/ks4HbiJk4Xjg9ir45jiO0zrp1zB70/XLcZzcUcB1GCsNSc8jCGwpV6clzhnw9c5yynHay7PHX52ZraPPHZuZLadzUPrW9wCCdrl+ObnF9WvHox0alhvKVhjNbFQ1HXEcx0lF+4ZrHsvTshSO4zh5HXJuizQvvSBpH2BvEnN/zOz6znLKcRynPGrXcI7rl+M4+aJ9GpYX2qwwSvoW4YsDexPm/nwc+Dvggus4TtfQnDrmEOAnuH45jpMn0mtYbkjzlvQk4EjgFTP7HOH7pV37UUzHcXZs0r8l/S5cvxzHyRsFfEs6TYVxg5k1A1sk9QNeA4Z3rlu1zbgJa5h271Ncd9+THHfmq7mwVcs+vba0ga9O2p1TP7wnp04Ywx+mDexyn2q5vLO29Q6MMJyTZgNz/cqeWr7n8mYnj/qVpa1a96lV0mpYzkhTYZwraWfgGsKb0w8D/+hMp1pD0toWxyfHb6UWiro644xLlnLhSaM4dcIYjpi4mhGjN3aprVr3qb6bMfmby7jm7qf40W3P8KfpA3nh6R5d5lOtl3eWtsohS7cB6yrpl6Rr4xdgHm/1OoEfS1os6VFJByTOfVbSM3H7bEV/a0S/oLbvubzZgfzpV5a2at2nSqTUr7btVEnDIEWF0cz+w8xWm9nVwMeAz8ahHacDjNl/Pcue784rL/ZgS2Mds2/ZmUOOfrNLbdW6T7sM3sLo/TYA0LtvM8P32MSK5Q1d5lOtl3eWtsqSfkj6xTb0azpwTIUrfRwYHbfJwM9g6zq13yJ8MWY88C1J78omc/mmlu+5vNmB/OlXlrZq3aeKZDckPZ0qaVjZCqOkA1puhDXNuiVrqHlA0iBJN0t6KG6HxfBbJH0m7p8m6ddx/9QYb0FM1zuGT4818fslLZE0KXGNr8Y0j0r6dkd93eXdjby+rPvW4xXLGxg4pLFLbdW6T0leeak7zz7eiz0PWN9lPtV6eXfWb5ekHT2MvSvpl5ndA6yqcKmJwPUWmAPsLGkIcDTwVzNbZWZvAH+lsmiXz0uB9Atq+57Lm52W5EG/srRV6z5VIqsexmpqWKW3pH9QyUfgI5UMdwK9JM1PHA8Abo37PwIuN7O/SxoBzAT2ItSm75P0HPAV4OAY//dmdg2ApP8GvkB4kxLCW5WHA3tG+zMkHUWonY8nLGR+q6QPxR9qK5Imx2vSk95Z5dvJiA3r6vjOKSM5/aKl9NmpgK+oOdtIP79nFDA7cbwsbmn1axjwUuL45RhWLrwcrl/OduH6VWOk07CBkuYmjqea2dR2XikrDau4cPcR7XSqs9lgZmNLB5JOBkoL8n4U2Fva+gP0k9TXzF6V9E3gLuBTZlaqhe8ThXZnoC9BoEv8MU6Sf0LS4Bh2VNweicd9CQL8NsGNP+TU4MCAVtsHK19pYNDQzVuPBw5p7NDwQpa2at0ngC2N8J1TRvKRT7/B4f/UseGFPOatln0qS/uGaxbmZOHumtAvqO17Lm92SuRJv7K0Ves+lSW9hq3IiX4B6V56KQJ1wMFmNjZuw8ysNMl8X2AlMDQRfzpwppntC3ybxIK+wKbEvhJ//ydhfw8z+0VHHF00vzfDRm1m8PBNdGtoZsLE1cyZ1bFVPrKyVes+mcEPvzKC4aM3cexpr3fIRpY+1Xp5Z2mrLOnnMG4vS3n7W9W7xbBy4R2hMPoFtX3P5c0O5E+/srRV6z5VpHrL6mSmYam+9FIAZgFnAd8HkDTWzOZLGk+Y8Lk/cLekWWb2HLATsFxSA3ASbQv9TOA7kn5tZmslDQMazey19jra3CSuumAYl9ywhLp6mHXTAF54umfbCTvRVq37tPDBPtw5YwCj9trAFz86BoDPfX0Z4498q0t8qvXyztJWOar4HdZbgTMl3USYHP6mmS2XNBO4JDFJ/Cg6/n3qwugX1PY9lzc7kD/9ytJWrftUiSJqmMxyuDpkK0haa2Z9E8cnA+PM7ExJA4GrCPN+uhGGWr4EPAh8zswelvQvwLmEuUunA18DXgceAHYys5MlTQduM7MZLa8p6UvAKfHya4F/M7Nny/nbTwPsIB2ZWf6dysxcNj8zW0cPHZuZLacyD9idrLFV7VpwrMfw4bbbOeemirvkvK/MqzSkI+lGwpesBgKvEt4abAAws6sVxomvJEwGX0/Qk7kx7eeB/4qmLjaz6ypcx/XLKYvrV3G5w2ZU1JjWSKthbekXVE/DIEWFMV7sJOC9ZnZRnJT9bjN7sGLCHRwX3OrigltMOlJh7LnbcNvtS+kqjM9+7SvzgCtw/WoXrl/VxfWruHSkwphWw579WtsVxmqSZg7jT4FDgBPj8VuE1rDjOE7XkP5LLyNw/XIcJ2/U6JdeDjKzM4CNAHG9nu6VkziO43Qi6V966eP65ThO7qjeSy+Zkeall0ZJ9UT3JQ0CfBEox3G6jHZMGDfXL8dx8kYVX3rJjDQ9jD8G/gDsKuli4O/AJZ3qleM4TiXS9zC+huuX4zh5oxZ7GM3s15LmAUcS1vP6pJk92emeOZmz+PKD246Ugj3OnZOJnSzxid47EO34bBbhk1lfw/Wr8Lh+OTVD+zQsN7RZYYxvFa4H/pQMM7MXO9Mxx3GcsqQfVO6O65fjOHmjgBNj0sxh/DOhc1SELwqMAhYB7+9EvxzHccrSjtb5HsBtuH45jpMjarKHMX5+aiuSDgD+o9M8chzHyY4nkuuYuX45juN0jHZ/S9rMHiZ8XsbpIOMmrGHavU9x3X1PctyZr+bC1q43PsvIb8xl+KULtsufLH3KYznlzU6t+1SWDn5L2vUrG/J2z7l+uU959aksBXzppc0Ko6QvJ7bzJN0ALKuCb0kfTNIPEsfnSZpSTR+yoq7OOOOSpVx40ihOnTCGIyauZsTojV1ua834QSyfvFeH0naGT3ksp7zZqXWfyhInjKfZgMGuX9mSx3vO9ct9yqNPZUmvX7kiTQ/jTomtB2FO48TOdKoVNgGfjt9cLTRj9l/Psue788qLPdjSWMfsW3bmkKPf7HJbG3fvR1Of+g6l7Qyf8lhOebNT6z5VpDnlFjTO9StD8njPuX65T3n0qSLp9CtXVKwwxgVvdzKzb8ftYjP7tZllXN1uky3AVOAdH1+UNFLS3yQ9KunO+FY3kqZL+rGk+yUtkTQphveN8R6W9JikiQk7T0q6RtJCSbMk9Yrndpf0F0nzJN0rac+OZmSXdzfy+rJtH5pYsbyBgUMau9xWVmTlUx7LKW92at2ncoh29TDWu35lp1+Qz3suK/KYN/epuD6VI62G5Y2yFUZJ3cysCTisiv5U4irgJEn9W4T/BPilme0H/Jqw0HiJIcDhwCeA78awjcCnzOwA4AjgB5JKH20cDVxlZu8HVgPHxvCpwFlmdiBwHuH72o7jdBXp5zD27RoH34Hrl+M42yjgHMZKb0k/CBwAzJd0K/A7YF3ppJn9vpN9extmtkbS9cDZwIbEqUOAT8f9XwHfS5z7o5k1A09IGhzDBFwi6UOETt9hQOncc2Y2P+7PA0ZK6gscCvxumy7TozUfJU0GJgP0pHer+Vj5SgODhm7eejxwSCMrljeUz3gFsrSVFVn5lMdyypudWvepLO1rfa93/cpOvyCf91xW5DFv7lNxfSpLTnsQ2yLNHMaewErgI4SW7j/Hv13BFcAXgD4p429K7JfU8iRgEHCgmY0FXiXksWX8JkKFug5YbWZjE1urs6vNbKqZjTOzcQ2tazKL5vdm2KjNDB6+iW4NzUyYuJo5s1p2OqQjS1tZkZVPeSynvNmpdZ8qkr6HsQ7Xr8z0C/J5z2VFHvPmPhXXp4rUWA/jrpK+DDzOtoW7S3RJVsxslaTfEkT32hh8P3ACoXV+EnBvG2b6A6+ZWaOkI4D3tHHNNZKek/R/zex3cfhnPzPr0PoNzU3iqguGcckNS6irh1k3DeCFp3u2nbCTbQ2+/hl6LV5D/botjJzyMCuP2Y23Dt61y3zKYznlzU6t+1SR9Aq0AXgM169M9Avyec+5frlPefSpIjmsELaFzFr3WtJy4Ge8XWhLmJld1JmOtfBlrZn1jfuDgeeA75nZFEnvAa4DBgKvA58zsxclTQduM7MZSRvxTcU/EeY2zQUOBj4eL3Wbme0T458H9I3XGEUoiyFAA3BTW/nvpwF2kI7MsBS2n1r+FqtTTB6wO1ljq1rTmLL0GjLc3vvZL6eK+8SlX15GmMOXxPXL9ctxMuEOmzEv+XGANKTVsCcu/XK7bXcmlXoYl1dTVCtREtu4/ypsm2BjZi8Qhptapjm5NRtmtoIwb6g19knEvyyx/xxwTMe8dxwnU9o3XLPczL7dec60jeuX4zhvI6dDzm1RaQ5ju1r9juM41aIdy+q0bUs6RtIiSYslnd/K+cslzY/b05JWJ841Jc7dmlkGHcepaYqoX5V6GPM1HuE4jlMio9a5wlqzVwEfA14GHpJ0q5k9sfVSZucm4p8F7J8wsSG+fOI4jpOeDDSs2vpVtofRzFa1w2/HcZyqkWEP43hgsZktMbPNwE1U/hLMicCN258Dx3F2ZIqoX2mW1XEcx8kX6ZfVaYthwEuJ45dj2DuIL6iMAv6WCO4paa6kOZI+2a48OI6z41JA/ao0JO3UGHl8O7CW33zMKm+Qz/x1Fe38bNZASXMTx1PNrOVb02k5AZgRv4BV4j1mtlTSe4G/SXrMzJ7toH2nAnl8Bly/0pHH/HUl7dCwXOmXVxgdxyke6SuMK9pYlmIpMDxxvFsMa40TgDPe5obZ0vh3iaTZhPlBXmF0HKcy6TQsV/rlQ9KO4xSODOcwPgSMljRKUneCqL7jbUFJewLvAv6RCHuXpB5xfyBwGPBEy7SO4zgtKaJ+eQ+j4zjFI6O3pM1si6QzgZlAPXCtmS2UdBEw18xK4nsCYcHr5JX3An4uqZnQ+P5u8u1Ex3GcsmSgYdXWL68wOo5TPDJc9NbMbgdubxH2zRbHU1pJdz+wb3aeOI6zw5Bdo7dq+uVD0l3AuAlrmHbvU1x335Mcd+arubCVR592vfFZRn5jLsMv7fBnbzP3yfNWfVvvwEDN6Tanc6jle86f8bbJY96ytNWp+gWpNSxvFK7CKGk3SbdIekbSs5J+FMfuy8U/R1LvcuerTV2dccYlS7nwpFGcOmEMR0xczYjRG7vUVh59AlgzfhDLJ+/VobSd4ZPnrfq2ypHll16qjWtYtnby6lMtP+N5y1uWtqqhX1BM/SpUhVGSgN8DfzSz0cD7gL7AxRWSnUPi261dzZj917Ps+e688mIPtjTWMfuWnTnk6De71FYefQLYuHs/mvrUdyhtZ/jkeau+rbJktw5jVXENy95OXn2q5Wc8b3nL0lZV9AsKqV+FqjACHwE2mtl1AHE9oXOBz0vqI+kySY9LelTSWZLOBoYCd0m6C0DSz+JClQslfbtkWNLzkr4t6WFJj8W3ioh2r5X0oKRHJFVaRb1Ndnl3I68v29aZsGJ5AwOHNHaprTz6lCV5LKesyGPeqlFOBe5hdA3L2E5efcoKz1t1bVWrnIqoX0V76eX9wLxkgJmtkfQicAowEhgb3xwaYGarJH0ZOMLMVsQkF8TweuBOSfuZ2aPx3AozO0DSfwDnRZsXAH8zs89L2hl4UNIdZraupXOSJgOTAXrmp0PAcWqLnLa+U5JbDXP9cpwqUVANK1oPYyUmAD83sy1Q8VvYx0l6GHiEIN57J879Pv6dRxBugKOA8yXNB2YDPYERrRk2s6lmNs7MxjXQo9WLr3ylgUFDN289HjikkRXLG9rIWutkZSuPPmVJHsspK/KYt6qUU0GHpNtgAl2oYWn0C2r7nvNnvLrs0PdAAfWraBXGJ4ADkwGS+lGmAtcSSaMIre4jzWw/4M8E8SyxKf5tYlvvq4BjzWxs3EaY2ZMdzcCi+b0ZNmozg4dvoltDMxMmrmbOrP5daiuPPmVJHsspK/KYt84uJ1Hot6RdwzK2k1efssLzVl1b1SintBqWN4o2JH0n8F1JnzGz6+OQzA+A6cAzwGmS7koO5wBvATsBK4B+wDrgTUmDgY8TWtyVmAmcJeksMzNJ+5vZIx3NQHOTuOqCYVxywxLq6mHWTQN44emebSfsRFt59Alg8PXP0GvxGurXbWHklIdZecxuvHXwrl3mk+et+rbKIcth8zsdrmEZ28mrT7X8jOctb1naqoZ+QTE1TFYwpyUNB34K7EnoIb2d0OJuAr4HHAM0AteY2ZWSzgLOBJaZ2RGSpgOHAi8BbwK3mtl0Sc8D48xshaRxwGVmNkFSL+CKmKYOeM7MPtGWn/00wA7SkRnmvDbJ6gP3efy4fVZ5g3zmLwsesDtZY6vUnjR9Bg63vSaemyruvGu/Mq+Nb7FWnSJomOtXOly/0pHH/GXFHTaj3RqTVsPypl9F62HEzF4C/rnM6S/HLRn/J8BPEscnl7E7MrE/lzCfCDPbAJy2HS47jpMxeXyDMC2uYY7jFFHDCldhdBzHyeOEcMdxnNQUUMO8wug4TuEoYuvccRynRBE1zCuMjuMUC8vnG4SO4zipKKiGeYXRcZziUcDWueM4zlYKqGFeYewkNg3vw+KvbP9bZrX8dhnUdv6yzFstv43ZXkQxh3OKhOtXOmo5f65fnUdRNcwrjI7jFI+CLQfmOI7zNgqoYV5hdByncBSxde44jlOiiBrmFUbHcYqFgZq62gnHcZwOUlANK9q3pGuCXW98lpHfmMvwSxdst61xE9Yw7d6nuO6+JznuzFe73I77VF07ebyXsrbVKpZyS4GkYyQtkrRY0vmtnD9Z0uuS5sftlMS5z0p6Jm6f3e58FYBav+fyZqfWfcrj/dTp+gWF1K9cVxglNcUMPi7pd5J6d9DOf2Xt2/awZvwglk/ea7vt1NUZZ1yylAtPGsWpE8ZwxMTVjBi9scvsuE/VtQP5u5eytlUOWbqtTTvhW85XEb7JvDdwoqS9W4n6GzMbG7dpMe0A4FvAQcB44FuS3pWw7fpVgTzec3mzU+s+Qf7up2roF+Rfv1oj1xVGYEPM4D7AZuD0DtrJleBu3L0fTX3qt9vOmP3Xs+z57rzyYg+2NNYx+5adOeToN7vMjvtUXTuQv3spa1utYoQJ42m2thkPLDazJWa2GbgJmJjSk6OBv5rZKjN7A/gr4TvQJVy/KpDHey5vdmrdJ8jf/dTp+gXpNaxtOlO/3kHeK4xJ7gX2kNRH0rWSHpT0iKSJsLXb9feS/hK7V78Xw78L9Iot/V/HsD9KmidpoaTJpQtIWivpYkkLJM2RNDiGD5J0s6SH4nZY9bP/TnZ5dyOvL+u+9XjF8gYGDmnsMjvuU3XtZEkey7sSWfUwAsOAlxLHL8ewlhwr6VFJMyQNb2dacP16B3m85/Jmp9Z9ypI8llMlCqZfQEEqjJK6EbpcHwMuAP5mZuOBI4DvS+oTo44Fjgf2BY6XNNzMzmdbS/+kGO/zZnYgMA44W9IuMbwPMMfMPgDcA5waw38EXG5mHwSOBaZ1YnYdx2mL9HMYB0qam9gmt26wIn8CRprZfoRW+C/bk9j1y3Gcd1AQ/UqS97eke0maH/fvBX4B3A/8i6TzYnhPYETcv9PM3gSQ9ATwHt5egy5xtqRPxf3hwGhgJWHY6LYYPg/4WNz/KLC3pFL6fpL6mtnapNH4Y04GqH9XxakAmbDylQYGDd289XjgkEZWLG/oMjvuU3XtZEkey7scMkPNqdekWGFm4yqcX0rQgBK7xbCtmNnKxOE04HuJtBNapJ2dOHb9qkAe77m82al1n7Ikj+VUjnZoWFfq1zvIew9jqWU91szOimP0Ao5NhI8wsydj/E2JtE20UiGWNIEgoIfElvgjBNEGaDTbOnEgmb4OODhxzWEtxRbAzKaa2TgzG1fft0/L05mzaH5vho3azODhm+jW0MyEiauZM6t/l9lxn6prJ0vyWN6VyHBI+iFgtKRRkroDJwC3vu1a0pDE4b8AJb2ZCRwl6V1xsvhRMayE61cF8njP5c1OrfuUJXksp0oUQL/eQd57GFtjJnCWpLPMzCTtb2aPtJGmUVKDmTUC/YE3zGy9pD2BNN8smgWcBXwfQNJYM5vf0QwMvv4Zei1eQ/26LYyc8jArj9mNtw7etd12mpvEVRcM45IbllBXD7NuGsALT/dsO2En2XGfqmsH8ncvZW2rLKk7GNswY7ZF0pkEXakHrjWzhZIuAuaa2a2EHr1/AbYAq4CTY9pVkr5DEG2Ai8xsVRuXdP2K5PGey5udWvcJ8nc/VUW/IBMNq7Z+yXL8eRpJa82sb4uwXsAVwKGElvNzZvYJSScD48zszBjvNuAyM5st6VJCzfph4PPAH4GRwCJgZ2BKjLf1epImAZ8ws5MlDSS8ur4XoZJ9j5lVfOOxx4jhNvQr52x3GdTKtzOd7aNWv8X6gN3JGlultmNuY6edd7MD/s+XUsW957avzWtjSKfTcP3K3/3mdA21ql8Ad9iMdmtMWg3rSv1qjVz3MLYU2xi2ATitlfDpwPTE8ScS+/8J/Gci+sfbup6ZzQBmxP0VhMnojuN0NQakn8PYZbh+OY7TKgXRsJbkusLoOI7TKsXTWsdxnG0UUMO8wug4TuFox1vSjuM4uaOIGuYVRsdxCkfKNwgdx3FySRE1zCuMjuMUi22L2jqO4xSPgmqYVxg7iR4vrcvlG11OMcnqXqqFtxVFWPjW6Txcv5wscf16O0XVMK8wOo5TPJq72gHHcZztoIAa5hVGx3GKhRVzwrjjOA5QWA3zCqPjOAXDoIDDOY7jOIFiaphXGB3HKRxFfMPQcRynRBE1rK6rHdgRGTdhDdPufYrr7nuS4858NRe23Kdi2snS1q43PsvIb8xl+KULtsufLH0qi1m6zekUavk5yJsd9ykdhdIvKKR+5b7CKGkXSfPj9oqkpYnj7i3izpaUm+8utkZdnXHGJUu58KRRnDphDEdMXM2I0Ru71Jb7VEw7WdtaM34Qyyfv1aG0neVTqxioOd2WB1zDOtdOHn2q5bzl1afC6Bek1rC8kfsKo5mtNLOxZjYWuBq4vHRsZpu72L12M2b/9Sx7vjuvvNiDLY11zL5lZw45+s0uteU+FdNO1rY27t6Ppj71HUrbWT6VpUA9jK5hnWsnjz7Vct7y6lOh9AsKo19Jcl9hbA1JR0p6RNJjkq6V1KOVOGsT+5MkTY/7gyTdLOmhuB0Ww6dEW7MlLZF0diL9v0l6MPYI/FxSh+/KXd7dyOvLtnUqrFjewMAhjV1qy30qpp2sbWVFNXxSs6Xa8oprWD6fg7zZcZ+qT7V8KqJ+FbHC2BOYDhxvZvsSXtz5YjvS/4jQwv8gcCwwLXFuT+BoYDzwLUkNkvYCjgcOiz0ETcBJrRmWNFnSXElzG9nUvlw5jpOeAvUwtkIuNcz1y3GqSAH1q4hvSdcDz5nZ0/H4l8AZwBUp038U2FtS6bifpL5x/89mtgnYJOk1YDBwJHAg8FBM0wt4rTXDZjYVmBqMDmj11175SgODhm4bhRo4pJEVyxtSut45ttynYtrJ2lZWdLpPRiEXvU2QSw1Lo19Q289B3uy4T9WnKj4VVMOK2MOYlqTg9Uzs1wEHJ+YQDTOz0tBPslndRKhQC/hlIv4YM5vSUacWze/NsFGbGTx8E90ampkwcTVzZvXvUlvuUzHtZG0rKzrbJ2HI0m0Fp6Y1LI/PQd7suE/Vpxo+pdWwvFHEHsYmYKSkPcxsMfDvwN2txHs1DsUsAj4FvBXDZwFnAd8HkDTWzOZXuN6dwC2SLjez1yQNAHYysxc64nxzk7jqgmFccsMS6uph1k0DeOHpnm0n7ERb7lMx7WRta/D1z9Br8Rrq121h5JSHWXnMbrx18K5d6lNZciim7cA1LEM7efSplvOWV58KpV9QSA2TFchpSVOAtcAjwGWECu9DwBfNbJOk2cB5ZjZX0iTgUuB1YC7Q18xOljQQuArYK6a/x8xOL9k2s8vitR4HPmFmz0s6Hvg6oWXfCJxhZhW/Xt5PA+wgHZltATjOdrL48oMzsbPHuRVv/9Q8YHeyxlap7Zjb6N97qB085tRUcWfNv2iemVVcpkbSMYR5gfXANDP7bovzXwZOAbYQ9OTzpcqWpCbgsRj1RTP7lzauNYUCaJjrl5NH8qZfAHfYjDY1piVpNSxv+lWoHsYWwyj7t3J+QmJ/BjCjlTgrCBPAK9nGzPZJ7P8G+E0HXHYcpxPIargmvi18FfAx4GXCPL9bzeyJRLRHgHFmtl7SF4HvsU1DNsQXSVLhGuY4DmSjYdXWr1qew+g4Tq2S3VvS44HFZrYkrol4EzDx7Zeyu8xsfTycA+yWaV4cx9nxKKB+eYXRcZyCkbKymE5whwEvJY5fjmHl+ALwv4njnnEpmjmSPtnurDiOswNSTP0q1JC04zgORnsmjA+UNDdxPDUuH9NuJP0bMA74cCL4PWa2VNJ7gb9JeszMnu2IfcdxdhDSa1iu9MsrjI7jFI/0a5itaGPS+FJgeOJ4txj2NiR9FLgA+HBc5xAAM1sa/y6JL6zsD3iF0XGcyqTTsFzpl1cYHWcHIqu3A2cum5+JnfFHr287UiuoObNVbx8CRksaRRDaE4B/fdu1pP2BnwPHmNlrifB3Aevj280DgcMIE8odx+kE8qZfAPVDOpYuIw2rqn55hdFxnGJhQEbfWTWzLZLOBGYSlqW41swWSroImGtmtxLWO+wL/C5+KaW0/MRewM8lNRPmg3+3xduJjuM47yQjDau2fnmF0XGcgpHtd1bN7Hbg9hZh30zsf7RMuvuBfTNzxHGcHYTsNKya+uUVRsdxikeBPjjgOI7zDgqoYb6sThcwbsIapt37FNfd9yTHnflqLmy5T8W0k0efXlvawFcn7c6pH96TUyeM4Q/TBnbYVlmyW1bH6QB5u+fy6FMt562WfaqKfkEh9asmKoySLpd0TuJ4pqRpieMfxM/jtJb2ZElDq+AmAHV1xhmXLOXCk0Zx6oQxHDFxNSNGb+xSW+5TMe3k1af6bsbkby7jmruf4ke3PcOfpg/khad7dMhWq5Tm/6TZCsKOqGG1/BzUct5q3adO1y9Ir2E5oyYqjMB9wKEAkuqAgcD7E+cPBe4vk/ZkoF1iK6nDQ/lj9l/Psue788qLPdjSWMfsW3bmkKPf7FJb7lMx7eTVp10Gb2H0fhsA6N23meF7bGLF8oYO2Wodg+amdFtx2OE0rJafg1rOW6371Pn6Bak1LGfUSoXxfuCQuP9+4HHgLUnvktSD8DbQUZIekvS4pKkKTCIsZPlrSfMl9ZJ0oKS7Jc2LrfwhAJJmS7oiLqL5pY46usu7G3l9WfetxyuWNzBwSGOX2nKfimknrz4leeWl7jz7eC/2PKBjy+e0Sg32MLIDalgtPwe1nLda9ylJp+gXeA9jV2Jmy4AtkkYQWuL/AB4gCPA44DHgSjP7oJntA/QCPmFmM4C5wEnxA9xbgJ8Ak8zsQOBa4OLEpbqb2Tgz+0GVsuY4hWXDujq+c8pITr9oKX12ymzdxECNzWF0DXOcfNGp+gWF1K9aekv6foLQHgr8kPA9xUOBNwnDPUdI+hrQGxgALAT+1MLGGGAf4K9xvaJ6YHni/G8qOSBpMjAZoCe9W42z8pUGBg3dvPV44JDGDnd3Z2XLfSqmnbz6BLClEb5zykg+8uk3OPyfOjbEVJEcimkGdKmGpdEvyOc9lzefajlvte4TVEG/oJAaVhM9jJHSHKB9CcM5cwit89Lcn58SWt37AtcAPVuxIWChmY2N275mdlTi/LpKDpjZ1Nh6H9dA65NkF83vzbBRmxk8fBPdGpqZMHE1c2b1b2dWs7XlPhXTTl59MoMffmUEw0dv4tjTXu+QjTauUHM9jJEu1bA0+gX5vOfy5lMt563Wfep8/YLUGpYzaq2H8TxgiZk1Aask7UyYD3RqjLNCUl9gEjAjhr0F7BT3FwGDJB1iZv+Q1AC8z8wWZuVkc5O46oJhXHLDEurqYdZNA3jh6dZ0v3q23Kdi2smrTwsf7MOdMwYwaq8NfPGjYwD43NeXMf7Itzpk7x0Y0JS/CeEZsENpWC0/B7Wct1r3qdP1CwqrYbIc1mI7gqR64A3gx2Z2YQybDhxiZmMk/TdwIvAK8DTwgplNkXQscAmwgdCaHwP8GOhPqFBfYWbXxA9zn2dmc9P4008D7CAdmWUWHSc3ZPct6ZeYu2Cj2pOmf8OuduiAY1PF/ctrV88zs3Edcq7K5EnDXL+cWibbb0kvbrfGpNWwvOlXzfQwxhZ5vxZhJyf2LwQubCXdzcDNiaD5wIdaiTchG08dx9k+8vkG4fbiGuY4OwrF1LCaqTA6jrODYGDWCW8tOo7jVIOCaphXGB3HKR4FbJ07juNspYAa5hVGx3GKR43MvXYcZwelgBrmFUbHcYqFWSHfMHQcxwEKq2FeYewk3uKNFXfYjBfaiDYQWJHB5bKyk6WtWvaplvOWylb9kGzsAO9J59Lbsebizf8pElXWryxt1bJPtZy3LG1lpV+pbLEDaZhXGDsJMxvUVhxJc7N4ZT4rO+5Tde24Tx0ln4va1hLV1K8sbdWyT7Wct1r36Z0UU8O8wug4TrEwCjlh3HEcByishnmF0XGc4lHAJSkcx3G2UkANq6VvSReRqTmzk6WtWvaplvOWpa0sfdqKAdZsqbY0SDpG0iJJiyWd38r5HpJ+E88/IGlk4tzXY/giSUdnlsliUOv3XN58quW8ZWkrjz69jbQaloZq6lfNfBrQcZwdg34aYAfVfSxV3Duaf1vx01rxc3xPAx8DXgYeAk40sycScf4D2M/MTpd0AvApMzte0t7AjcB4YChwB+G7zcV7/dFxnKqRVsPypl/ew+g4TvGw5nRb24wHFpvZEjPbDNwETGwRZyLwy7g/AzhSkmL4TWa2ycyeAxZHe47jOJUpoH75HMYOIOmTwB+AvczsqfbGk3QyMMvMlrVxnVTxYtwm4DGgAdgCXE+4AfYys+9GX55OtjxapD8dWA9cB7yZ2G6K6c8BpprZ+hh/rZn1bcXO28JjHsaZ2Zlt5aEVW+uAU+N1t9umJAN+aGZficfnAX3NbEp7fUvY3A24Ctib0AC7DfhqfHhbi38OsRwTv1k34Engs6XybacP/wX8HLgzBr0baAJej8fjk/5Img2cZ2ZzU9q/HHjBzK6IxzOBl8zslHj8A2Cpmf2wlbQnk/IeTstbvDHzDpsxMGX0npKS+ZxqZslhpmHAS4njl4GDWtjYGsfMtkh6E9glhs9pkXZYSr+6jFrWLzO7XlIz8AJBv6DrNazezHpmZC9TDXP9qr5+Qbs0LFf65T2MHeNE4O/xb0finUzoAm6LtPEANpjZWDN7P6F7+uPAAWb23Xj+kwRReAeSupnZ1WZ2PbABuJUgGmMT6c8Beqf0JSvqgH/N0N4m4NOS0lY2KhJbab8H/mhmo4H3AX2BiyskO4dt5Vj6zfYBNgOnd9CV/zKzldHWWOBq4PLScTnxbwf3AYcCSKojrE32/sT5Q4H7y6Q9mfT3MPEaFRuyZnaMmY1Lue3T4rhT5iQVjFrWLwiVja8m7v+u1rAsO2Yy0zDXr61UVb+gXRqWL/0yM9/asREeqKWEh2tRDKsHLgMeBx4FzorxXgMeBDYCMwm191sJgraRUKPvRXjQ3iJU1l4mLAQ6CWgmLBq6Pto+GXgk7j9NmK/wCPAq4YF9mNDi2xN4L7AWuBI4PNreFP9eAMwGrojXWw68AvwtprmP0LpfQGj1PRt9aQSWER6uZuDmGGcO8O3oT3O0+QhhTsTZ0YcpwA2EVuNGQg/AYbH8ZgKrYz5fB06N4U2EXoIm4FxgJHAv8Hws20OBQcDdwBpgVbT7a+AW4DPAgbGsVhJ6Lm6PeVgQf6uL47VmEFph62IZnR7DpxP+ab4Vy++3ifvg4Rj+GDAxhu8Tr3Nd/O1K58+KZdQc7a+O1/oZMDf69BDQB7g2Xmt5LPvHgK8TxP2vsUyWxzK+OZbPfODX0Yen4m/wPPBiTH9t/G0vjn8fAwbH/UHRzuLo82GJsIei7Vej7Z8Cz8Syfj7+LquBbwJL4m+4gtBjcFy0vyja6BV/j7uBeYTffUi0O5twP84FvlLF5/kQYGbi+OvA11vEmQkcEve7xfypZdxkvLxu1Lh+JXQjqV/3Ep4Di/ftm/Fe3UB4HhYQdOORmP9G4AGy0zAj3P8lDVsUy/Zh4J8Iz9lTBA27K+6/BHwm2rg4ltG8aG9ZPL6ZcA9OIehUaXRoU8zHiJj+oRh/HfAGMCmG/3/xuFTuE4F+MeypaGNj/G2/HMthczx+K/pyI65fsIPoV5cLWNE24CTgF3H//ngDfZFQ4egWwwcQKiuvxhv3fuD8+HdGvOHGxXh948N1UEx7NzAn7m8Evhf3z4437/uASwgieA6wM0HgNsV4/wFMi/vrgV8AkwmiMAnoEW/qOYThh/sJLcYpwDcID+8bwHPxIVkRb6znCRXJ5witZgOWxev8lvBgim2VvGcID/satont68ARhBbeG4RhjANjOT0Ww58iiP9QgqDfxjZBWRC3F4FfxXzcQPgH9yZh/sWTwD+AfyYIyGME0RoQy/M3MS/9Cf8Mbo95eInwz7GO8A9pbQyfRRCSOkKrdB3wIcKD91Xg8uj34pj/kbFsvkf4rX8H/Fu8/p0EIRxIGDbYEsO7ESq4TwPXxPjPA1+LYecQ7oslwA+AzxH+Wb0/nl/b4h69FLgwXutpwvDD9dGvfyaI2y9jnLWxDA8n3B+/i2V4A3B4tDeC8I9iBPCnWJ6XACfEcv87cHA81xB/mz8TnoHZhOE34rn7gUHx+Hjg2rg/G/hpFzzP3WK5jgK6E+6v97eIcwZwddw/gW2NhvfH+D1i+iWE4ccu16kdVb9iuma26ddm4IaEPy8QnuW92fY8HBXjXsg2bXsmhmWhYaUK43y26deVwGhCQ/ZwYEK8zjPRh7mE53dCtDE6kYdfEfTh+4QpA1MIFcZlhEr53tGfP8a8LSI81/WE5+zlaOsc4Kq4n9SwhQTN/Svh+fgtcFqMt4EwRFz6fe7B9Qt2EP3yOYzt50TgR3H/png8ivCDbAEws1WSvkAQ078SHsavEITsW4QKSSnepwkP8s/DCAH9CK20EnfFvyuBRjN7WtJRhIdoCkEgShU1CC2fT7fw+Shgd4LAXEioLK0hVH5usTAfBYIYbCCI8UiCEA+IvvcjiPuLZtYsaTOwU7Tfi9Ar8Ej0pSGGrWPbPKJSvMsT+zsDHyEI7N1mtkLS74Cjefvk2w1mNlZSf4LQTgCOieU0IsatIyyB0I8gAP3j8aWEfx5/i369N/q4KB4/F68xCLgg5u17wHdi+NCYz4cTfo9mW6V0L8I/kGGEFi+Ef6CjCa3ZA2JZbib0iNYTftOmuL+A8FuuJwjiRwitxqHAZ4GehNb4QEKF88OxfN5F+IfQI+YnyUGE36Nv9H00QWBPIvyT/Uos891j/I8S/sn0j9sGwrDg3vG+gFC5PQIYTuil/XvMz8aYhy9Ev9bEfL1JaEQkGUPogf1rtFsf81biN1QZC3N6ziS0rusJ/wAWSroImGtmtxIqLb+StJjQM3FCTLtQ0m+BJwjlc4bl/w3pWtcvop8bCfrVDThK0nzC877WzJqBJ2Ka26LdoYTepkmE53BzzNcGtl/DmiwMtRI17PZY7ocT9PXKWNaKPvdm22jNHdGX30V/uwOfiGGnxOsuiNfZidBL1yipd7S/mKBNPWPZ9iX8niUOk/RovFZSwzYQKvtbJM0DBknqS9CbX8T5i70IWrUG1y/YAfTL5zC2A0kDCA/ENEnPE3qYjisTbzxBrHYmPEgbCDfpO6ITJmuPjaJyKqEnr0Rp/kYz2x4sEcT2bzHNy/E8BOHtJum9bBv+FGGIpTSvZxShddxYJquHA9OAYwmtjtsIrdf/BS6KcRoT/hjwWPTFgBPMbDfgNIJIJ/N6cIy3mCAsmxM2krQ8hiDorxKGD35LEM86Qq/E3TFvwwgVtm6E3oxG4NJ4zQ0E4fo3glCUWsclNrXwtcTvE7/PejP7BUG8moGnYvirBHHs28JmUzyuIwx9LAOOKNmK1xxmZgMJrdp6QrkvAz5sZiMILeL6GFfx/D2EYa8RybKSNIFQKZ5GqOQ+Ev0CMItNy4RfFn07mNDDfGssw62/VfT1PEJPymBCD8kcwu/XK17jeMKE7F6E1vtV9s6J+AIW2ra5Sfua2VGJ8+voAszsdjN7n5ntbmYXx7BvRrHFzDaa2f81sz3MbLyZLUmkvTimG2Nm/9sV/qdlB9KvelroV+L5vywZMT4PIvTU/SmhYV83s33pHA1bQxjKHRfDDiZU/u42s2FmtjaWw3uIw7eJ8oXQYN4rxum5zfTbrpcs60cJw6RjzWwPQuUAQqVuKHBgQsMGxrDkK7pJDWvm7fr1Aq5fJWpev7zC2D4mAb8ys/eY2UgzG07ooVoAnJaY7PoZ4P8RhjlPjPGeJzxEpxG60XeKwjwL6CVpUiLtorjfTKiAQHgwe0rag9CaOJ/QzQ+h4pSkgTBx+I54PJPQGtsZQNL7CL/9A8DnYmsUwsNTSv8G4UEfSuh9eyteZ7dWymUBMDq2QAE2S9qV0MJMsogwfFxib8LQ1J7AJ2N5TCK0Ah8iiMFOifj9CS06I7T26gnl96lSBElj4+4o4IOE+VoXShoVw3eOfswg9FKWeI0w9wVCZbDU0loGfCSRN8W89ScMQfWS9D8EcS8NZ68mlPlpbHvGuhHuFRF+e8Vz64A3JQ0mTPQvzXcsXWz/FmU4s5XzjZJK/9RKLeyNwB4EUQT490SekrxKEM+zieUYy3AWb/+tVhJ6NjYQhHsVoSx7EXouNgPHKCwKOymWy3sI903pN1xE6Kk4JF6nQVJy8rnTuewo+gXv1C8IFcxRvJOZhIp0sqFXets3Cw1LNj77E/QBwjMJb3+ex8bdXYH9CCMUw2NPLtFWP8JztZbQ+5b07YS43y36NTPG6RntlypTELTRgBMlHUHQsAsI2vgWb78nepnZGkKl7/iEL024fu04WA7m1RRlIwyvHNMi7GzCiws/JHTtLiDMuzgGGEtoSS0gVHRmx3gv8fZJ45MJD/8GgtB9Mdp+jdCKnU+ozMxn26Txp+LfhQRxK83zezbaOo8wV+RKgrheH6+5gTCcei+hhXt+9PsVwpBBE6ES0xj/ls4tjeeWRt/Wsm2e3ySCeD/GtuGgxwhDPU+xbf7PNwnd9qXJ1KVJzjNjvltOGF9LGEouvfQyOqZ9kfCQryW0iP9GaLU/QfhH89MY54D4Gzwe4zYR/hE+R2i9NgLz47V+F31+NJbDuhg+nTDh+rG4NRH+eQ2M5fhUvNZmwj/F6fE36Ub4rV+N5Xcm4Z/VEzHv6wjiO51wv9xJmBR+KmHC9eZo+7b4O5XKsVc8vybm4zbCsPuThJd9ehDmQb3Ktpd1lsQ8lH6v2YT5RdPjb/ccYa7qCsI/s6tj/kq/1ROJa95DWNKiVDabCEPu/x3zuZYw7LGM0Oo/lrdPGh/LtmdiIdt+69nEuUK+uX7RQf2K1zW26dcb0d6CeJ3VwF2leIlyuDbGLWlYSWOy0LAt8folDXuJ8KxdGs//Jub7LcKz1yOe/1a08aXo9wK2vUj0IKEXbgvb5jCeTtDCR2N46aWXBwja9Fgsu5K2DYx5XEPoydwc7bwv/jale2IZ2+Z6fyuW69royyO4fpV8qnn98i+9OF2OpCkEMbisrbiO4zh5wzXM2RHwIWnHcRzHcRynIt7D6DiO4ziO41TEexgdx3Ecx3GciniF0XEcx3Ecx6mIVxgdx3Ecx3GciniF0ek0JDVJmi/pcUm/S6yX1hFb00trvUmaJmnvCnEnSDq0A9d4XtLAtOEt4qxt57WmSDqvvT46jlMdXL8qxnf92gHxCqPTmWywsCL+PoR1uU5PnkwsCtsuzOwUM3uiQpQJhM8+OY7jdBTXL8dJ4BVGp1rcC+wRW8/3SrqV8D3Xeknfl/SQpEclnQbhcyqSrpS0SNIdhC8fEM/NljQu7h8j6WFJCyTdGVfqPx04N/YO/B9JgyTdHK/xkKTDYtpdJM2StFDSNN75TdN3IOmPkubFNJNbnLs8ht8paVAM213SX2KaeyXtmUlpOo5TTVy/XL92eDrUQnKc9hBb4h8H/hKDDgD2MbPnomi9aWYflNQDuE/SLGB/wuf/9iZ8//MJwmr/SbuDgGuAD0VbA8xslaSrSSyiK+kG4HIz+7ukEYSvMuxF+GrB383sIkn/H+ED9G3x+XiNXsBDkm42s5VAH8LH3s+V9M1o+0xgKnC6mT0j6SDCV2g+0oFidBynC3D9cv1yAl5hdDqTXpLmx/17gV8QhloeNLPnYvhRwH7a9i3a/oTPZ30IuNHMmoBlkv7Wiv2DgXtKtix8H7Q1PgrsLW1tgPdT+Db0h4BPx7R/lvRGijydLan07erh0deVhM9k/SaG/z/g9/EahwK/S1y7R4prOI7T9bh+uX45CbzC6HQmG8xsbDIgCs+6ZBBwlpnNbBHvnzL0ow442Mw2tuJLaiRNIIj3IWa2XtJsoGeZ6Bavu7plGTiOUwhcv1y/nAQ+h9HpamYCX5TUACDpfZL6ED7wfnycIzQEOKKVtHOAD0kaFdMOiOFvATsl4s0CziodSBobd+8B/jWGfRx4Vxu+9gfeiGK7J6GHoEQdUOpl+FfCUNEa4DlJ/zdeQ5I+0MY1HMcpDq5fzg6DVxidrmYaYX7Pw5IeB35O6Pn+A/BMPHc98I+WCc3sdWAyYfhkAduGVP4EfKo0aRw4GxinMCn9Cba97fhtgmAvJAztvNiGr38Bukl6EvguQfBLrAPGxzx8BLgohp8EfCH6txCYmKJMHMcpBq5fzg6Df0vacRzHcRzHqYj3MDqO4ziO4zgV8Qqj4ziO4ziOUxGvMDqO4ziO4zgV8Qqj4ziO4ziOUxGvMDqO4ziO4zgV8Qqj4ziO4ziOUxGvMDqO4ziO4zgV8Qqj4ziO4ziOU5H/H6ClY6KvJ1nZAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 720x288 with 4 Axes>"
      ]
     },
     "metadata": {}
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [],
   "outputs": [],
   "metadata": {}
  }
 ],
 "metadata": {
  "orig_nbformat": 4,
  "language_info": {
   "name": "python",
   "version": "3.8.10",
   "mimetype": "text/x-python",
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "pygments_lexer": "ipython3",
   "nbconvert_exporter": "python",
   "file_extension": ".py"
  },
  "kernelspec": {
   "name": "python3",
   "display_name": "Python 3.8.10 64-bit ('torch': conda)"
  },
  "interpreter": {
   "hash": "3b894362b46030d773ba9e34d3080b25469638a075aff61e52143fa49479ec0e"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}